#ifndef PICOCALC_CLOCK_VERSION_H
#define PICOCALC_CLOCK_VERSION_H

#define PICOCALC_CLOCK_VERSION_MAJOR 0
#define PICOCALC_CLOCK_VERSION_MINOR 8
#define PICOCALC_CLOCK_VERSION_PATCH 43
#define PICOCALC_CLOCK_VERSION_STRING "0.8.43"
#define PICOCALC_CLOCK_TEST_SEQUENCE "0.8.43-life-clock-overlay"

#define PICOCALC_CLOCK_BUILD_PROFILE "release"

#endif
