#ifndef PICOCALC_CLOCK_VERSION_H
#define PICOCALC_CLOCK_VERSION_H

#define PICOCALC_CLOCK_VERSION_MAJOR 0
#define PICOCALC_CLOCK_VERSION_MINOR 8
#define PICOCALC_CLOCK_VERSION_PATCH 4
#define PICOCALC_CLOCK_VERSION_STRING "0.8.4"
#define PICOCALC_CLOCK_TEST_SEQUENCE "calendar-mode"

#define PICOCALC_CLOCK_BUILD_PROFILE "release"

#endif
